version: "3"
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=db_test
    volumes:
      - ./server/db_data:/var/lib/mysql
  spring:
    build: ./server/

    ports:
      - "8088"
    links:
      - "mariadb"
    depends_on:
      - "mariadb"
    restart: always
    environment:
      - CONFIG_LOCATION=file:/server/src/resources/prod.properties
  # angular:
  #  build: ./client/
  # links:  "spring"
  #depends_on: "spring"
  #ports: "80:80"
volumes:
  db_data: {}
