version: "3.3"
services:
  mariadb:
    image: mariadb:latest
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=db_test
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/db_init:/docker-entrypoint-initdb.d
  spring:
    image: isnob46/virtuallabs_spring
    build: ./server/
    container_name: virtualLabs-backend
    ports:
      - "8080:8080"
    expose: 
      - "8080"
    depends_on:
      - mariadb
    environment:
      - DB_SERVER=mariadb
      - DB_NAME=db_test
    restart: always
  angular:
    image: isnob46/virtuallabs_angular
    build: ./client/
    container_name: virtualLabs-frontend
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/app/dist
    depends_on:
      - spring
volumes:
  db_data: {}
