version: "3"
services:
    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=db_test

  #server:
    #build: .
    #container_name: virtuallabs_server
    
