### STAGE 1: Build ###
FROM maven:3.6.1-jdk-11-slim AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -f pom.xml clean package -Dmaven.test.skip=true 

### STAGE 2: Run ###
FROM adoptopenjdk/openjdk11
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh","-c","java -Dspring.datasource.url=jdbc:mysql://$DB_SERVER:3306/db_test -jar /app.jar"]