version: "3"
services:
    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=db_test
        volumes:
        - ./db_data:/var/lib/mysql
        - ./db_init:/docker-entrypoint-initdb.d
    #server:
        #build: .
        #container_name: virtuallabs_server    
volumes: 
    db_data: {}
 
    
